services:
  backend:
     build: ./server
     ports: 
        - "4000:4000"
     networks:
        - mern 
     environment:
        MONGODB_URL: ${MONGODB_URL}
        JWT_SECRET : ${JWT_SECRET}
        MAIL_HOST :  ${MAIL_HOST}
        MAIL_USER :  ${MAIL_USER}
        MAIL_PASS :  ${MAIL_PASS}
        RAZORPAY_KEY : ${RAZORPAY_KEY}
        RAZORPAY_SECRET : ${RAZORPAY_SECRET}
        CLOUD_NAME : ${CLOUD_NAME}
        API_KEY : ${API_KEY}
        API_SECRET : ${API_SECRET}
     depends_on:
         - mongodb


  frontend:
     build: ./frontend
     ports:
       - "3000:3000"
     networks:
       - mern


  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks :
        - mern
      volumes:
        - mongo-data:/data/db


networks:
  mern:
    driver: bridge


volumes:
  mongo-data:
     driver: local