name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'server/**'

  deploy:
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        if: needs.filter.outputs.frontend == 'true'
        run: curl -X POST ${{ secrets.FRONTEND_DEPLOY_HOOK }}

      - name: Deploy Backend
        if: needs.filter.outputs.backend == 'true'
        run: curl -X POST ${{ secrets.BACKEND_DEPLOY_HOOK }}
